// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleFlashcards.Data;

namespace SimpleFlashcards.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210924153655_Migr18_FlashcardSubtopic")]
    partial class Migr18_FlashcardSubtopic
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleFlashcards.Entities.Files.FileInfoWordImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("FileInfoWordImages");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Files.FileInfoWordPronunciation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid?>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WordId");

                    b.ToTable("FileInfoWordPronunciations");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Flashcards.Flashcard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAllSubtopics")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Flashcards");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Flashcards.FlashcardWord", b =>
                {
                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.HasKey("FlashcardId", "WordId");

                    b.HasIndex("WordId");

                    b.ToTable("FlashcardWords");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInBan")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Ips.Ip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInBan")
                        .HasColumnType("bit");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Ips");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Ips.UserIp", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IpId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "IpId");

                    b.HasIndex("IpId");

                    b.ToTable("UserIps");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Maps.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Côte d'Ivoire"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 37,
                            Name = "China"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Congo (Congo-Brazzaville)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czechia (Czech Republic)"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini (fmr. Swaziland)"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Holy See"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 78,
                            Name = "India"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Myanmar (formerly Burma)"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 124,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 129,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Palestine State"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 150,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 163,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 164,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 184,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 187,
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Maps.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rank")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mandarin",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Spanish",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "English",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hindi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arabic",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Portuguese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bengali",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Russian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Japanese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Punjabi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 11,
                            Name = "German",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 12,
                            Name = "Javanese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 13,
                            Name = "Wu (inc. Shanghainese)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 14,
                            Name = "Malay (inc. Indonesian and Malaysian)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Telugu",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Vietnamese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Korean",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 18,
                            Name = "French",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Marathi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Tamil",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Urdu",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Turkish",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Italian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Yue (inc. Cantonese)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Thai",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Gujarati",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Jin",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 28,
                            Name = "Southern Min (inc. Hokkien and Teochew)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 29,
                            Name = "Persian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 30,
                            Name = "Polish",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Pashto",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Kannada",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 33,
                            Name = "Xiang",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 34,
                            Name = "Malayalam",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 35,
                            Name = "Sundanese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 36,
                            Name = "Hausa",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 37,
                            Name = "Odia (Oriya)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 38,
                            Name = "Burmese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 39,
                            Name = "Hakka",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 40,
                            Name = "Ukrainian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 41,
                            Name = "Bhojpuri",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 42,
                            Name = "Tagalog (Filipino)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 43,
                            Name = "Yoruba",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 44,
                            Name = "Maithili",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 45,
                            Name = "Uzbek",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 46,
                            Name = "Sindhi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 47,
                            Name = "Amharic",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 48,
                            Name = "Fula",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 49,
                            Name = "Romanian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 50,
                            Name = "Oromo",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 51,
                            Name = "Igbo",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 52,
                            Name = "Azerbaijani",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 53,
                            Name = "Awadhi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 54,
                            Name = "Gan",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 55,
                            Name = "Cebuano (Visayan)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 56,
                            Name = "Dutch",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 57,
                            Name = "Kurdish",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 58,
                            Name = "Serbo-Croatian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 59,
                            Name = "Malagasy",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 60,
                            Name = "Saraiki",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 61,
                            Name = "Nepali",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 62,
                            Name = "Sinhala",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 63,
                            Name = "Chittagonian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 64,
                            Name = "Zhuang",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 65,
                            Name = "Khmer",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 66,
                            Name = "Turkmen",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 67,
                            Name = "Assamese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 68,
                            Name = "Madurese",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 69,
                            Name = "Somali",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 70,
                            Name = "Marwari",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 71,
                            Name = "Magahi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 72,
                            Name = "Haryanvi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 73,
                            Name = "Hungarian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 74,
                            Name = "Chhattisgarhi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 75,
                            Name = "Greek",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 76,
                            Name = "Chewa",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 77,
                            Name = "Deccan",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 78,
                            Name = "Akan",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 79,
                            Name = "Kazakh",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 80,
                            Name = "Northern Min",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 81,
                            Name = "Sylheti",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 82,
                            Name = "Zulu",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 83,
                            Name = "Czech",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 84,
                            Name = "Kinyarwanda",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 85,
                            Name = "Dhundhari",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 86,
                            Name = "Haitian Creole",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 87,
                            Name = "Eastern Min (inc. Fuzhou dialect)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 88,
                            Name = "Ilocano",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 89,
                            Name = "Quechua",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kirundi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 91,
                            Name = "Swedish",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 92,
                            Name = "Hmong",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 93,
                            Name = "Shona",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 94,
                            Name = "Uyghur",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 95,
                            Name = "Hiligaynon/Ilonggo (Visayan)",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 96,
                            Name = "Mossi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 97,
                            Name = "Xhosa",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 98,
                            Name = "Belarusian",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 99,
                            Name = "Balochi",
                            Rank = 0.0
                        },
                        new
                        {
                            Id = 100,
                            Name = "Konkani",
                            Rank = 0.0
                        });
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.FlashcardSubtopic", b =>
                {
                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubtopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FlashcardId", "SubtopicId");

                    b.HasIndex("SubtopicId");

                    b.ToTable("FlashcardSubtopics");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.FlashcardTopic", b =>
                {
                    b.Property<Guid>("FlashcardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FlashcardId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("FlashcardTopics");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.Subtopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subtopics");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.Topic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Words.Translation", b =>
                {
                    b.Property<Guid>("WordId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WordId2")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("WordId1", "WordId2");

                    b.HasIndex("WordId2");

                    b.ToTable("Translations");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Words.Word", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PartOfSpeech")
                        .HasColumnType("int");

                    b.Property<string>("Transcription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Files.FileInfoWordImage", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Words.Word", "Word")
                        .WithMany("Images")
                        .HasForeignKey("WordId");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Files.FileInfoWordPronunciation", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Words.Word", "Word")
                        .WithMany("Pronunciations")
                        .HasForeignKey("WordId");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Flashcards.Flashcard", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Flashcards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Flashcards.FlashcardWord", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Flashcards.Flashcard", "Flashcard")
                        .WithMany("FlashcardWords")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Words.Word", "Word")
                        .WithMany("FlashcardWords")
                        .HasForeignKey("WordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationRoleClaim", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationRole", "Role")
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Maps.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserClaim", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserLogin", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserRole", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Base.ApplicationUserToken", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Identities.Ips.UserIp", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Ips.Ip", "Ip")
                        .WithMany("UserIps")
                        .HasForeignKey("IpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("UserIps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.FlashcardSubtopic", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Flashcards.Flashcard", "Flashcard")
                        .WithMany("FlashcardSubtopics")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Topics.Subtopic", "Subtopic")
                        .WithMany("FlashcardSubtopics")
                        .HasForeignKey("SubtopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.FlashcardTopic", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Flashcards.Flashcard", "Flashcard")
                        .WithMany("FlashcardTopics")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Topics.Topic", "Topic")
                        .WithMany("FlashcardTopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.Subtopic", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Topics.Topic", "Topic")
                        .WithMany("Subtopics")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Topics.Topic", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Words.Translation", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Words.Word", "Word1")
                        .WithMany("Translations1")
                        .HasForeignKey("WordId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimpleFlashcards.Entities.Words.Word", "Word2")
                        .WithMany("Translations2")
                        .HasForeignKey("WordId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleFlashcards.Entities.Words.Word", b =>
                {
                    b.HasOne("SimpleFlashcards.Entities.Maps.Language", "Language")
                        .WithMany("Words")
                        .HasForeignKey("LanguageId");

                    b.HasOne("SimpleFlashcards.Entities.Identities.Base.ApplicationUser", "User")
                        .WithMany("Words")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
